<a href="https://colab.research.google.com/github/hanseul1215/ESAA_study/blob/master/%EB%84%98%ED%8C%8C%EC%9D%B4_%EA%B0%9C%EB%85%90_%EA%B3%B5%EB%B6%80_%2B_%ED%95%84%EC%82%AC_%EC%98%88%EC%8B%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy** 

*   빠른 배열 기반의 연산을 가능하게 하고, 데이터 핸들링을 가능하게 하는 패키지

---


# **넘파이 ndarray**

*   np.array()를 사용해 변환 -> 인자로 주로 리스트 객체 사용
*   shape 변수로 행, 열, 차원 확인
*   그 연산의 특성상 같은 데이터 타입만 가능 (dtype으로 확인/ astype()으로 변환)
---
1) arange,zeros,ones()  

*   ndarray를 쉽게 생성
*   arange() : array를 range()로 표현
 
2) reshape() 
* ndarray를 특정 차원 및 크기로 변환
* reshape(-1,1) : 2차원, 여러개의 행, 1개 열 
    
3) indexing : ndarray내 특정 데이터 선택

* 단일 값 추출 : axis=0 (행), axis=1 (열)
* 슬라이싱 :  ':'를 이용해 연속한 값을 반환
* 팬시인덱싱 : 입력된 인덱스 값을 반환
* 불린인덱싱 : 특정 조건에 해당하는 인덱스 값을 반환
    
4) 행렬의 정렬
* np.sort() : 원 행렬 유지, 정렬된 행렬 반환
* ndarray.sort() : 원 행렬을 정렬한 형태로 반환
* argsort(): 정렬된 행렬의 인덱스를 반환
* 내림차순 정렬 : [::-1]

5) 선행대수 연산 - 행렬 내적, 전치 행렬
* 행렬 내적 : np.dot() (왼쪽 행렬 열 개수 = 오른쪽 행렬 행 개수)
* 전치 행렬 : transpose()

In [ ]:
import numpy as np

In [ ]:
array1 = np.array([1,2,3])
print(type(array1), array1.shape)

array2 = np.array([[1,2,3],
                  [3,4,5]])
print(type(array2), array2.shape)

array3 = np.array([[1,2,3]])
print(type(array3), array3.shape)

<class 'numpy.ndarray'> (3,)
<class 'numpy.ndarray'> (2, 3)
<class 'numpy.ndarray'> (1, 3)


In [ ]:
print("1:%d , 2:%d, 3:%d" %(array1.ndim, array2.ndim, array3.ndim))

1:1 , 2:2, 3:2


In [ ]:
list1 = [1,2,3]
array1 = np.array(list1)
print(type(array1))
print(array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
int32


In [ ]:
# 데이터 크기가 더 큰 타입으로 형 변환
list2 = [1,2,"test"]
array2=np.array(list2)
print(array2,array2.dtype)

list3 = [1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [ ]:
float=array1.astype('float64')
print(float,float.dtype)
int=array3.astype('int32')
print(int,int.dtype)

[1. 2. 3.] float64
[1 2 3] int32


In [ ]:
se_array = np.arange(10)
print(se_array,se_array.dtype, se_array.shape)

ze_array = np.zeros((3,2), dtype='int32')
print(ze_array,ze_array.dtype, ze_array.shape)
on_array = np. ones((3,2))
print(on_array,on_array.dtype, on_array.shape)

[0 1 2 3 4 5 6 7 8 9] int32 (10,)
[[0 0]
 [0 0]
 [0 0]] int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]] float64 (3, 2)


In [ ]:
#reshape
array1 = np.arange(10)
array2 = array1.reshape(2,5)
array3 = array1.reshape(5,2)
print(array1)
print(array2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1= np.arange(8)
array3d = array1.reshape((2,2,2))
print(array3d.tolist(), array3d.shape)
# 3->2
array5 = array3d.reshape(-1,1)
print(array5.tolist(), array5.shape)
# 1->2 
array6 = array1.reshape(-1,1)
print(array6.tolist(), array6.shape)


[[[0, 1], [2, 3]], [[4, 5], [6, 7]]] (2, 2, 2)
[[0], [1], [2], [3], [4], [5], [6], [7]] (8, 1)
[[0], [1], [2], [3], [4], [5], [6], [7]] (8, 1)


In [ ]:
# 인덱싱
## 단일값 추출
array1 = np.arange(1,10)
value = array1[2]
print(value, type(value))
array1[0] = 9
array1[8] = 0
array1

3 <class 'numpy.int32'>


array([9, 2, 3, 4, 5, 6, 7, 8, 0])

In [ ]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d, array2d[1,2]) # axis=0 행 , axis=1 열 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 6


In [ ]:
#슬라이싱
import numpy as np
array1 = np.arange(1,10)
array3 = array1[0:3]
print(array3, type(array3))
print(array3[1])

[1 2 3] <class 'numpy.ndarray'>
2


In [ ]:
array2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
#팬시 인덱싱
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1],2]
print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]


In [ ]:
#불린 인덱싱
array3 = array1d[array1d >5]
print(array3)
bool = np. array([False, False, False, False, False,  True,  True,  True,  True])
array4 = array1d[bool]
print(array4)

[6 7 8 9]
[6 7 8 9]


In [ ]:
#정렬
o_array = np.array([3,1,9,5])
sort1=np.sort(o_array)
print(sort1)
print(o_array)
print(np.sort(o_array)[::-1])

[1 3 5 9]
[3 1 9 5]
[9 5 3 1]


In [ ]:
sort2=o_array.sort()
print(sort2)
print(o_array)


None
[1 3 5 9]


In [ ]:
o_array = np.array([3,1,9,5])
sort_indices=np.argsort(o_array)
print(type(sort_indices))
print(sort_indices)

<class 'numpy.ndarray'>
[1 0 3 2]


In [ ]:
name_array = np.array(['Jo',"mi","de","ft"])
score_array = np.array([85,70,90,100])
sort_indices = np.argsort(score_array)
print(sort_indices)
print(name_array[sort_indices])

[1 0 2 3]
['mi' 'Jo' 'de' 'ft']


In [ ]:
#선형대수 연산
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])
dot=np.dot(A,B)
print(dot)

[[ 58  64]
 [139 154]]


In [ ]:
A = np.array([[1,2],
             [3,4]])
tran=np.transpose(A)
print(tran)

[[1 3]
 [2 4]]
